routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('fix', 'Auth\LoginController@fix');

Route::get('/', 'Auth\LoginController@guest')->name('home');
Route::get('login', 'Auth\LoginController@admin')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('guest/qr', 'UserGuestController@qrCode')->name('user.guest.qr');
Route::get('user/guest', 'UserGuestController@index')->name('user.guest.index');

Route::get('seat', 'UserGuestController@seat')->name('seat');
Route::get('rundown', 'UserGuestController@rundown')->name('rundown');
Route::get('module', 'UserGuestController@module')->name('module');
Route::get('photo', 'UserGuestController@photo')->name('photo');
Route::get('quiz', 'QuizController@index')->name('quiz.index');
Route::get('quiz-end', 'QuizController@end')->name('quiz.end');

Route::middleware('auth')->group(function(){
    Route::get('user/admin', 'UserAdminController@index')->name('user.admin.index');
    Route::get('user/officer', 'UserAdminController@indexOfficer')->name('user.officer.index');
    
    Route::post('user/admin/create', 'UserAdminController@store')->name('user.admin.create');
    Route::post('user/guest/create', 'UserGuestController@store')->name('user.guest.create');
    
    Route::get('user/admin/list', 'UserAdminController@list')->name('user.admin.list');
    Route::get('user/guest/list', 'UserGuestController@list')->name('user.guest.list');
    Route::get('user/guest/{id}', 'UserGuestController@show')->name('user.guest.profile');
    Route::get('validate-guest', 'UserGuestController@validateGuest')->name('user.guest.validate');

    Route::post('user/admin/delete/{id}', 'UserAdminController@delete')->name('user.admin.delete');
    Route::post('user/guest/delete/{id}', 'UserGuestController@delete')->name('user.guest.delete');
    
    Route::post('quiz/create', 'QuizController@store')->name('quiz.create');
    Route::post('quiz/group', 'GameSessionController@group')->name('quiz.group');
});

app/UserAdmin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserAdmin extends Model{

    public $timestamps = false;

    public function getJobAttribute(){
        return $this->role == 'admin' ? 'Admin' : 'SPG';
    }

    public function getPotraitAttribute($value){
        return $value ? asset('uploads/admin/' . $value) : 'https://api.adorable.io/avatars/150/abott@adorable.png';
    }

    public function user(){
        return $this->morphOne('App\User', 'userable');   
    }

    public function scopeActive($query, $isActive=true){
        return $query->whereIsActive($isActive);
    }

}

app/UserGuest.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class UserGuest extends Model{
    
    public function getIsVerifiedAttribute(){
        return $this->verified_at && $this->verified_by;
    }

    public function getPotraitAttribute($value){
        return $value ? asset('uploads/guest/' . $value) : 'https://api.adorable.io/avatars/150/abott@adorable.png';
    }

    public function getVerifiedAtAttribute($value){
        return $value ? Carbon::parse($value) : null;
    }

    public function getCreatedAtAttribute($value){
        return $value ? Carbon::parse($value) : null;
    }
    
    public function user(){
        return $this->morphOne('App\User', 'userable');
    }

    public function createdBy(){
        return $this->belongsTo('App\User', 'created_by');
    }

    public function verifiedBy(){
        return $this->belongsTo('App\User', 'verified_by');
    }

    public function scopeActive($query, $isActive=true){
        return $query->whereIsActive($isActive);
    }

}

resources/views/admin/index.blade.php
@extends('layouts.admin')

resources/views/admin/index_officer.blade.php
@extends('layouts.app')

@section('content')
  <div class="full flexCenter">
    <div class="box-login" style="overflow: hidden;">
      <div class="w100" >
        <div class="w100 mb20" >
          <div class="centered">
            <span class="img-verifikasi-tamu">
              <img src="{{ asset('assets/image/woman.png') }}">
            </span>
          </div>
        </div>
        <div class="w100 mb15" >
          <div class="centered">
            <div class="">
              <p class="fw800 f20"><b>Siap Menjalankan Tugas!</b></p>
            </div>
          </div>
        </div>
        <div class="w100 mb15" >
          <div class="centered">
            <div class="">
              <p class="f12">Anda sudah dapat memverifikasi tamu dengan <br>membaca QR code tamu Anda</p>
            </div>
          </div>
        </div>
        <div class="w100 mb15 mt50" >
          <div class="centered">
            <a href="{{ route('logout') }}" class="btn btn-peach" style="width: 250px; color:white;">LOGOUT</a>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/login.blade.php
@extends('layouts.app')

@section('content')
  <div class=" full flexCenter">
    <div class="box-login" style="overflow: hidden;">
      <div style="text-align: center;width: 100%">
        <div class="mb30" style="text-align: center;display: inline-block;">
          <div class="box-img-profile">
            <div class="box-img-profile-inner">
              <img class="img-login" src="{{ asset('assets/image/logo.png') }}">
            </div>
          </div>
        </div>
        <form action="{{ route('login') }}" method="POST">
          {{ csrf_field() }}
          <input type="hidden" name="as" value="officer">
          <div class="mb15">
            <input class="inputLogin" type="text" name="username" placeholder="Username" required>
          </div>
          <div class="mb15">
            <input class="inputLogin" type="password" name="password" placeholder="Password" required>
          </div>
          <div class="mb15">
            <button class="btn btn-login">Login</button>
          </div>        
        </form>
        <div class="mb15">
          <a class="aSmallGrey white" href="{{ route('home') }}" style="">Masuk sebagai tamu</a>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/user_admin.blade.php
@extends('layouts.admin')

@section('content')
  <div class="container-fluid">
    <div class="text-right mB-10">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        <i class="ti-plus"></i> Tambah Petugas
      </button>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="bgc-white bd bdrs-3 p-20 mB-20">
          <h4 class="c-grey-900 mB-20">List Petugas</h4>
          <table id="dataTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th></th>
                <th>Username</th>
                <th>Nama</th>
                <td>Tugas</td>
                <td></td>
              </tr>
            </thead>
            <tbody>
              @foreach($users as $user)
              <tr>
                <td width="15%"><img src="{{ $user->potrait }}" alt="user potrait" width="100"></td>
                <td>{{ $user->user->username }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->job }}</td>
                <td>
                  <form action="{{ route('user.admin.delete', $user->id) }}" method="POST">
                    {{ csrf_field() }}
                    <button class="btn btn-xs btn-danger" onclick="return confirm('Anda akan menghapus data ini ?')"><i class="ti-trash"></i> Hapus</button>
                  </form>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div> 
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Tambah Petugas</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        </div>
        <form action="{{ route('user.admin.create') }}" id="addForm" method="POST" enctype="multipart/form-data">
          <div class="modal-body">
            {{ csrf_field() }}
            <div class="form-group">
              <label for="username">Username</label>
              <input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="password">Password</label>
                  <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="repassword">Konfirmasi Password</label>
                  <input type="password" class="form-control" id="repassword" name="repassword" placeholder="Konfirmasi Password" required>
                </div>
              </div>
            </div>
            <hr>
            <div class="form-group">
              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" name="name" placeholder="Name" required>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="role">Tugas</label>
                  <select name="role" id="role" class="form-control" required>
                    <option value="">Pilih Tugas</option>
                    <option value="admin">Admin</option>
                    <option value="officer">SPG</option>
                  </select>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="potrait">Foto</label>
                  <input type="file" class="form-control" id="potrait" name="potrait" required accept="image/x-png,image/gif,image/jpeg">
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
            <button type="submit" class="btn btn-primary">Simpan</button>
          </div>
        </form>
      </div>
    </div>
  </div>
@endsection

@section('js-bottom')
  <script>
    $(function(){
      $("#addForm").validate({
        rules: {
          username:{
            required: true,
            minlength: 3,
            maxlength: 30
          },
          password:{
            required: true,
            minlength: 6,
            maxlength: 60
          },
          repassword:{
            equalTo: '#password',
          },
          name:{
            required: true,
            minlength: 3,
            maxlength: 60,
          },
          role: 'required',
          potrait: {
            required: true,
          }
        }
      });
    });
  </script>
@endsection

resources/views/admin/user_guest.blade.php
@extends('layouts.admin')

@section('content')
  <div class="container-fluid">
    <div class="text-right mB-10">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        <i class="ti-plus"></i> Tambah Tamu
      </button>
    </div>        
    <div class="row">
      <div class="col-md-12">
        <div class="bgc-white bd bdrs-3 p-20 mB-20">
          <h4 class="c-grey-900 mB-20">List Tamu</h4>
          <table id="dataTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th></th>
                <th>Nama</th>
                <th>Seat</th>
                <th>Kode</th>
                <th>Tedaftar oleh</th>
                <th>Waktu</th>
                <th>Diverifikasi Oleh</th>
                <th>Waktu</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              @foreach($guests as $guest)
              <tr>
                <td width="10%"><img src="{{ $guest->potrait }}" alt="user potrait" width="100"></td>
                <td>{{ $guest->name }}</td>
                <td>{{ $guest->seat }}</td>
                <td>{{ $guest->code }}</td>
                <td>
                  @if($guest->created_by)
                    {{ $guest->createdBy->username }}
                  @else
                    <span class="badge badge-warning">Menunggu Verifikasi</span>
                  @endif
                </td>
                <td>
                  @if($guest->created_at)
                    {{ $guest->created_at->format('d-m-Y H:i') }}
                  @else
                    <span class="badge badge-warning">Menunggu Verifikasi</span>
                  @endif
                </td>
                <td>
                  @if($guest->verified_by)
                    {{ $guest->verifiedBy->username }}
                  @else
                    <span class="badge badge-warning">Menunggu Verifikasi</span>
                  @endif
                </td>
                <td>
                  @if($guest->verified_at)
                    {{ $guest->verified_at->format('d-m-Y H:i') }}
                  @else
                    <span class="badge badge-warning">Menunggu Verifikasi</span>
                  @endif
                </td>
                <td>
                  <form action="{{ route('user.guest.delete', $guest->id) }}" method="POST">
                    {{ csrf_field() }}
                    <button class="btn btn-xs btn-danger" onclick="return confirm('Anda akan menghapus data ini ?')"><i class="ti-trash"></i> Hapus</button>
                  </form>    
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Tambah Tamu</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        </div>
        <form action="{{ route('user.guest.create') }}" id="addForm" method="POST" enctype="multipart/form-data">
          <div class="modal-body">
            {{ csrf_field() }}

            <div class="form-group">
              <label for="name">Nama</label>
              <input type="text" class="form-control" id="name" name="name" placeholder="Name" required>
            </div>

            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="seat">Seat</label>
                  <input type="text" class="form-control" id="seat" name="seat" placeholder="Seat" required>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="code">Code</label>
                  <input type="text" class="form-control" id="code" name="code" placeholder="Code" required>
                </div>
              </div>
            </div>

            <div class="form-group">
              <label for="potrait">Foto</label>
              <input type="file" class="form-control" id="potrait" name="potrait" accept="image/x-png,image/gif,image/jpeg" required>
            </div>
            
            <div class="form-group">
              <label for="desc">Keterangan</label>
              <textarea name="desc" id="desc" cols="10" rows="5" class="form-control" placeholder="Keterangan"></textarea>
            </div>
  
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
            <button type="submit" class="btn btn-primary">Simpan</button>
          </div>
        </form>
      </div>
    </div>
  </div>    
@endsection


@section('js-bottom')
  <script>
    $(function(){
      $("#addForm").validate({
        rules: {
          name: {
            required: true,
            minlength: 3,
            maxlength: 60,
          },
          seat: {
            required: true,
          },
          code: {
            required: true
          },
          potrait:{
            required: true
          }
        }
      });
    });
  </script>
@endsection